import type { SkillCategory } from './types'

export const SKILL_CATEGORIES: SkillCategory[] = [
  {
    id: 'business',
    title: 'Бизнес и карьера',
    icon: 'briefcase',
    color: 'business',
    subcategories: [
      { id: 'team-management', title: 'Управление командой' },
      { id: 'marketing-and-advertising', title: 'Маркетинг и реклама' },
      { id: 'sales-and-negotiations', title: 'Продажи и переговоры' },
      { id: 'personal-brand', title: 'Личный бренд' },
      { id: 'resume-and-interview', title: 'Резюме и собеседование' },
      { id: 'time-management', title: 'Тайм-менеджмент' },
      { id: 'project-management', title: 'Проектное управление' },
      { id: 'entrepreneurship', title: 'Предпринимательство' },
    ],
  },
  {
    id: 'art',
    title: 'Творчество и искусство',
    icon: 'palette',
    color: 'art',
    subcategories: [
      { id: 'drawing-illustration', title: 'Рисование и иллюстрация' },
      { id: 'photography', title: 'Фотография' },
      { id: 'video-editing', title: 'Видеомонтаж' },
      { id: 'music-and-sound', title: 'Музыка и звук' },
      { id: 'acting', title: 'Актёрское мастерство' },
      { id: 'creative-writing', title: 'Креативное письмо' },
      { id: 'art-therapy', title: 'Арт-терапия' },
      { id: 'decor-and-diy', title: 'Декор и DIY' },
    ],
  },
  {
    id: 'languages',
    title: 'Иностранные языки',
    icon: 'global',
    color: 'languages',
    subcategories: [
      { id: 'english', title: 'Английский' },
      { id: 'french', title: 'Французский' },
      { id: 'spanish', title: 'Испанский' },
      { id: 'german', title: 'Немецкий' },
      { id: 'chinese', title: 'Китайский' },
      { id: 'japanese', title: 'Японский' },
      { id: 'exam-preparation', title: 'Подготовка к экзаменам (IELTS, TOEFL)' },
    ],
  },
  {
    id: 'education',
    title: 'Образование и развитие',
    icon: 'book',
    color: 'education',
    subcategories: [
      { id: 'personal-development', title: 'Личностное развитие' },
      { id: 'learning-skills', title: 'Навыки обучения' },
      { id: 'cognitive-techniques', title: 'Когнитивные техники' },
      { id: 'speed-reading', title: 'Скорочтение' },
      { id: 'teaching-skills', title: 'Навыки преподавания' },
      { id: 'coaching', title: 'Коучинг' },
    ],
  },
  {
    id: 'health',
    title: 'Здоровье и лайфстайл',
    icon: 'lifestyle',
    color: 'health',
    subcategories: [
      { id: 'yoga-and-meditation', title: 'Йога и медитация' },
      { id: 'nutrition-and-wellness', title: 'Питание и ЗОЖ' },
      { id: 'mental-health', title: 'Ментальное здоровье' },
      { id: 'mindfulness', title: 'Осознанность' },
      { id: 'physical-training', title: 'Физические тренировки' },
      { id: 'sleep-and-recovery', title: 'Сон и восстановление' },
      { id: 'work-life-balance', title: 'Баланс жизни и работы' },
    ],
  },
  {
    id: 'home',
    title: 'Дом и уют',
    icon: 'home',
    color: 'home',
    subcategories: [
      { id: 'cleaning-and-organization', title: 'Уборка и организация' },
      { id: 'home-finances', title: 'Домашние финансы' },
      { id: 'cooking', title: 'Приготовление еды' },
      { id: 'houseplants', title: 'Домашние растения' },
      { id: 'repair', title: 'Ремонт' },
      { id: 'storage', title: 'Хранение вещей' },
    ],
  },
]
